### ISSUE TITLE
Toggle H1/H2

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#14]
When user click triggers `setSize()`, the highlighted text changes size as intended. When user click triggers same `setSize()`, it might be expected that the size application is undone. Basically, toggle font size application.

Also, it seems common in RTE to toggle formblock for h1/h2/h3. This, rather than 'fontSize' will enable the changing of line without highlighting

**Comment by dvnrsn** [comment]
https://github.com/CanopyTax/bandicoot/pull/15

**Comment by internettrans** [comment]
I don't understand this issue. Could you help explain it? `fontSize` and `heading` are two separate things you can do with document.execCommand. See https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand. What connection are you seeing between the two?

**Comment by dvnrsn** [comment]
I see now. In my implementation of bandicoot I had mistakenly understood useFontSize to be the option for h1/h2 blocks and not realized there was such thing as

```js
document.execCommand('formatBlock', false, '<h1>'); 
```

As a result I was trying to pigeonhole the useFontSize to do what one would expect the h1/h2 to do (toggle on and off, format the line even if there was no highlight). This issue and the tagged PR are now irrelevant. I will see if I can get headers into the docs so no one repeats my mistake
