### ISSUE TITLE
Need a means to acquire `isActive` for use-font-size

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#16]
use-document-query-command-state exposes `isActive` which gives the option to change a rich text button's color if bold/italic/underline etc. are active. font-size has no such feature but could use the add.

**Comment by internettrans** [comment]
When would `isActive` be false? When the rich text editor is not focused? Font size is inherently different from bold/italic/underline in that there is *always* a font size that is active whenever you're working in the rich text.

**Comment by dvnrsn** [comment]
This was asked in my confused state of trying to use useFontSize instead of useDocumentExecCommand for H1/H2. I have, however, addressed the formatBlock needs in this PR

https://github.com/CanopyTax/bandicoot/pull/18
