### ISSUE TITLE
Focus option

### ISSUE THREAD

**Issue by jairuzu** [CanopyTax/bandicoot#24]
There should be an option to focus the RichTextEditor when the initialHTML property is set.  Also, there should be a way to imperatively focus the RichTextEditor whenever desired through the ref.  Right now, it appears the only way to focus the RichTextEditor is to setHTML on the ref.

**Comment by internettrans** [comment]
I agree 👍

What do you think of this proposed API, in the [rich text editor ref](https://bandicoot.js.org/components/rich-text-editor.html#ref)?

```js
richTextEditorRef.current.focus()
```

Note that if you need a workaround for this right now, you can use `richTextContext.getContentEditableElement().focus()`. See https://bandicoot.js.org/context/rich-text-context.html#api for more details. I prefer not pushing people towards using RichTextContext directly when they're doing normal/basic, things, though, so I'll add the ability to do it through the richTextEditorRef

**Comment by jairuzu** [comment]
Thanks for the work-around info. Yeah, I think exposing an imperative focus() method on the Ref is great.  What do you think about also adding an optional bool property on the RichTextEditor such as `initialFocus` for a declarative approach?
