### ISSUE TITLE
Show placeholder text when blank

### ISSUE THREAD

**Issue by jairuzu** [CanopyTax/bandicoot#25]
Bandicoot appears to only show the placeholder text up to the point the RichTextEditor becomes focused/active. However, most DOM input elements show the placeholder text until content has actually been added.

**Comment by internettrans** [comment]
Thanks for the bug report - I might have time in the next day or two to look into this. @dvnrsn originally implemented the placeholder and might be able to look into it, too. Or if you want to look into it, @jairuzu, [here is the line of code](https://github.com/CanopyTax/bandicoot/blob/master/src/rich-text-editor.component.js#L139) that likely would need to change.

**Comment by jairuzu** [comment]
Yeah that is the line I thought would need changed. I too can try and look at it in the next couple of days.
