### ISSUE TITLE
JSX RichTextEditor and Control Button Order Matters Within RichTextContainer

### ISSUE THREAD

**Issue by jairuzu** [CanopyTax/bandicoot#26]
The JSX order of the `RichTextEditor` compared to certain control buttons matters within the `RichTextContainer` which creates for some confusing behavior/bugs.

For example,
```
<RichTextContainer>
  <ControlButtonWithUseLink />
  <RichTextEditor
    initialHTML={myHtml}
  />
</RichTextContainer>
```
works as expected.  In this case, the control button with useLink setups up the addNewHTMLListener (i.e. richTextContext.addNewHTMLListener(newHtml)) and _then_ the `initialHTML` gets set on the `RichTextEditor` which causes the `fireNewHtml` function to be called, processing the links as intended.

However,
```
<RichTextContainer>
  <RichTextEditor
    initialHTML={myHtml}
  />
  <ControlButtonWithUseLink />
</RichTextContainer>
```
does not work as expected.  In this case, the `RichTextEditor`'s `initialHTML` gets set before the useLink has had a chance to `addNewHTMLListener`s... which means the links don't get processed as expected since the `fireNewHTML` function is called before the listeners are listening.

One potential solution would be to change the `useLink`'s `useNewHtmlHandler` function (and any other custom hooks that rely on utilizing `addNewHTMLListener`s) to use the `useLayoutEffect` hook instead of the `useEffect` hook. As in...
```
function useNewHtmlHandlerLayout() {
  useLayoutEffect(() => {
    richTextContext.addNewHTMLListener(newHtml)
    return () => richTextContext.removeNewHTMLListener(newHtml)

    function newHtml() {
      if (richTextContext.getContentEditableElement()) {
        const anchorElements = richTextContext.getContentEditableElement().querySelectorAll('a')
        anchorElements.forEach(processAnchorElement)
      }
    }
  }, [processAnchorElement])
}
```

In this case, the `useNewHtmlHandler` function(s) would get synchronously called before the `RichTextEditor` component calls the `useEffect` for processing the `initialHTML` and subsequently calls `fireNewHTML`... aka...
```
useEffect(() => {
    if (props.initialHTML) {
      divRef.current.innerHTML = props.initialHTML
      richTextContext.fireNewHTML()
    }
  }, [])
```

**Comment by internettrans** [comment]
Ah, good catch. Yeah that is very confusing behavior. `useLayoutEffect` seems like it would probably work, although is there an even better way to safeguard against this that is more obvious in its implementation? One option that comes to mind is to maybe store the previous calls to `fireNewHtml()` during the initialization phase of RichTextContext, so that event listeners added right afterwards still work?

What do you think

**Comment by jairuzu** [comment]
I agree the `useLayoutEffect` solution isn't very obvious as to what it is trying to solve. If we went that route it would need comments for sure. If we can get a more naturally descriptive alternative working (such as processing the HTML at the end of initialization) I'm definitely good with that.

**Comment by jairuzu** [comment]
Sorry, i haven't got a pull request in for it yet, but what if we essentially just did a `fireNewHTML()` call when the `RichTextContainer` has finished mounting. We could put logic in there to make sure it only gets called if the editor has HTML. I think this would be more obvious than the `useLayoutEffect`. Thoughts?

**Comment by dvnrsn** [comment]
@jairuzu if you wrap your code in ```js it will have syntax highlighting.

```js
useEffect(() => {
    if (props.initialHTML) {
      divRef.current.innerHTML = props.initialHTML
      richTextContext.fireNewHTML()
    }
  }, [])
```

**Comment by dvnrsn** [comment]
I see no immediate danger in moving the `fireNewHTML` invocation up into the container as long as react waits to fire the effect until after the UEs of all children (which I understand to be the case) and contextValue doesn't change. I would actually prefer that to `useLayoutEffect`.
