### ISSUE TITLE
HTML sanitization

### ISSUE THREAD

**Issue by internettrans** [CanopyTax/bandicoot#3]
It would be great to have documentation for HTML sanitization, and possibly an example of how to add sanitization to bandicoot.

**Comment by dvnrsn** [comment]
#32 
TODO: Documentation

**Comment by jairuzu** [comment]
See bandicoot.js.org PR #15. https://github.com/CanopyTax/bandicoot.js.org/pull/15/files

**Comment by jairuzu** [comment]
@dvnrsn @joeldenning With the recent updates to the docs, do you think we can close this?

**Comment by internettrans** [comment]
Yeah let's close this
