### ISSUE TITLE
Line break on words

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#51]
![image](https://user-images.githubusercontent.com/9112811/61253234-85ab5880-a71d-11e9-9b61-c58f94f04c86.png)
I am getting words cut off. Need to investigate why contentEditable div is not respecting breaking on words

**Comment by dvnrsn** [comment]
Looks like [word-break](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break) is what I'm after. Also check out [overflow-wrap: break-word](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)

**Comment by dvnrsn** [comment]
![image](https://user-images.githubusercontent.com/9112811/61258555-8fd85180-a733-11e9-8174-52f9239e73ed.png)
Hmm, why is this on here?

**Comment by jairuzu** [comment]
I thought I fixed this here... https://github.com/CanopyTax/bandicoot/pull/38 are you not seeing this?

**Comment by internettrans** [comment]
yeah which version of bandicoot are you using?  That looks like an older version

**Comment by dvnrsn** [comment]
removed yarn link and 2.10 fixed this
