### ISSUE TITLE
conversion to <ol> loses h1

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#52]
![H1-to-ordered](https://user-images.githubusercontent.com/9112811/61309797-29dddf80-a7b0-11e9-8a94-ed718e111d0f.gif)
Is this the intended behavior? Should h1 be preserved in list as in google docs?

**Comment by internettrans** [comment]
Which browser was this in? Have you checked this in all browsers? 

The behavior you're seeing is very likely the browser's default behavior when you call `document.execCommand('insertOrderedList')` and have an h1 highlighted. With bandicoot, my intent has been to stick to browser default behavior whenever possible.

Is this something that users at Canopy are complaining about?

**Comment by dvnrsn** [comment]
It's not something I have a strong opinion about. It is proposed as a bug by QA but low priority to me.

FF preserves the H1. Safari mimics Chrome

**Comment by internettrans** [comment]
My preference is to chalk this up to “that’s how the browser chooses to do it.” Is also accept a PR that somehow makes it work, but such a PR would be pretty hard to pull off I think for such a small gain.

**Comment by internettrans** [comment]
Closing this since your thumbs up seems to indicate that you agree we'll just accept the browser behavior here.
