### ISSUE TITLE
Form submit beats bandicoot's save

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#64]
If I use bandicoot with an external button that invokes `fn` with state maintained outside of (but set by) bandicoot, the `fn` beats bandicoot's save. I remember we discussed this at one point with notes at Canopy. In that situation we introduced more state variables to be able to know if the note was saving and then included them in the dependency array in the useEffect that also watched variables that were changed on `submit`.

This seems a little convoluted to me but maybe it's the best/only way to succeed. The blur of the rich text editor executes before the clicking of save, but bandicoot introduces a timeout that I believe moves the execution of save() to the next tick.

We should document the "standard" way to think about this use case because it seems like it will be common.

[codesandbox](https://codesandbox.io/s/angry-pike-ftr8d)

**Comment by dvnrsn** [comment]
It might be best to not maintain the state of the contentEditable at all and just take advantage of bandicoot's getHTML()

**Comment by internettrans** [comment]
I would recommend just calling `getHTML()` inside of your onSubmit handler
