### ISSUE TITLE
cursor goes stationary after bold click

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#69]
(note: specific to Chrome)

enter text, click bold, enter text, click bold, enter text
cursor stays in one place and text produced to the right of the cursor (composing in a right to left fashion)

Multiple engineers (including myself) spent hours trying to debug this one at Canopy without success. Today while moving the component around (while drafting this message) I discovered finally the culprit. One of our parents was wrapping everything in a `<span>`. Move to `<>` and it seems to work...
![cursor-push-text-ahead](https://user-images.githubusercontent.com/9112811/66150526-9b207800-e5d2-11e9-98d6-e30d566b17cd.gif)

**Comment by dvnrsn** [comment]
[codesandbox](https://codesandbox.io/s/beautiful-shamir-mwy4r) that shows the problem. Should we add something in docs, perhaps "common hiccups", @joeldenning  or will this suffice for reference?

**Comment by dvnrsn** [comment]
maybe we even climb the tree and give a console warning?

**Comment by internettrans** [comment]
Hmm yeah this is worth adding docs for. A console warning would be cool, too.

**Comment by dvnrsn** [comment]
I believe this is done? not sure why still open
