### ISSUE TITLE
Multiple children each with RichTextEditor

### ISSUE THREAD

**Issue by dvnrsn** [CanopyTax/bandicoot#90]
If my react state is in parent but the children all edit that state, I can easily update everything except rich text editor. The parent will need to be informed with the refs to the rich text editor and run `getHTML` on all of them with updates on save. This seems much more complicated than an onChange?
[codesandbox](https://codesandbox.io/s/autumn-smoke-qfoq2)
![image](https://user-images.githubusercontent.com/9112811/81233501-004aaa80-8fb4-11ea-82ef-be62ac6a1972.png)

**Comment by dvnrsn** [comment]
I believe all we need to do here is something like:
```js  
function onInput() {
  props.onInput && props.onInput(getHTML())
}

<div contentEditable onInput={onInput} />
```

**Comment by internettrans** [comment]
> If my react state is in parent but the children all edit that state, I can easily update everything except rich text editor.

Could you explain this in more detail? You can update all props to RichTextEditor in the normal way by storing state in the parent and passing it down to the child component which then passes it into RichTextEditor.

> The parent will need to be informed with the refs to the rich text editor and run getHTML on all of them with updates on save.

Yes, with uncontrolled components you must go get the value of the input when you want to save it. The value is not stored in React state.

**Comment by internettrans** [comment]
From [these React docs](https://reactjs.org/docs/uncontrolled-components.html):

> To write an uncontrolled component, instead of writing an event handler for every state update, you can use a ref to get form values from the DOM.

**Comment by dvnrsn** [comment]
In the context of the codesandbox, the parent holds the state of tasks and the children simply call an update function any time the task properties change. When `author` input changes, the individual `<Task` component simply invokes an update function that updates the task array in the parent component. Thus the `tasks` array is kept up to date dynamically.

The presence of the rich text editor disrupts this dynamic updating. For good reasons it seems.

**Comment by dvnrsn** [comment]
#91 violates the intention of the rich text editor to be completely uncontrolled. I think [these points](https://github.com/CanopyTax/bandicoot/pull/91#pullrequestreview-407592298) are sound.

> The value of an uncontrolled component should never be stored in React state. Storing it in react state is the defining feature of controlled components.

While I am not as strictly committed to the uncontrolled component (I see how breaking the convention makes the rich text editor to use in cases like the original post), I do acknowledge there are advantages to thinking of bandicoot as strictly uncontrolled. The main advantage I see is not cycling state up and down. Also, points made below.

> Serializing and sanitizing the HTML on every input event is too costly of a performance overhead.

While I don't know enough about performance to have an opinion on whether or not the loss is worth it, it is absolutely the case that performance will be impacted by running sanitization and serialization on every input. This is why I made the `onInput` optional in the PR. But this becomes a bit of a foot gun especially for folks who might have a lot going on in the browser and longer rich text content. I do like the idea of not troubling bandicoot with doing so much on every input.

> onInput and other event handlers are given evt objects, not raw strings.
I agree. There is no real `onChange` in the context of the contentEditable. So it feels kind of hacky to use the `onInput` to then invoke a new api `onBandicootChange` with serialized and sanitized content.

The case could be made that it would be worth these costs to break the uncontrolled paradigm, but I think this might be easier solved by a better architecture in react of original post. Simply put: we acknowledge there is more work required of the consumer (especially in this situation) but it is worth maintaining the uncontrolled status of bandicoot.
